### ISSUE TITLE
What is the role of the default_value input for hyperparameters?

### ISSUE THREAD

**Issue by ifed-ucsd** [automl/ConfigSpace#105]

**Comment by mfeurer** [comment]
It is used as the default value in the [SMAC algorithm](https://github.com/automl/SMAC3) (which is the main software using the `ConfigSpace` package. Also, it is used when a deactivated hyperparameter becomes active, for example by changing the value of a hyperparameter other hyperparameters are conditioned on. Example: changing the kernel type in a support vector machine from linear to rbf activates the gamma hyperparameter which is then set to the default value.
