### ISSUE TITLE
Crash with numpy version lower than 1.16.0

### ISSUE THREAD

**Issue by vladvelici** [automl/ConfigSpace#107]
I think it actually needs `numpy>=1.16.0` to work.

Below are clean virtualenvs on an Ubuntu 16.04.4 LTS machine and Python 3.5.

Tried with 1.13.0:

    (npy13) vlad:~/Projects/test$ pip3 freeze
    ConfigSpace==0.4.7
    Cython==0.29.3
    numpy==1.13.0
    pyparsing==2.3.1
    typing==3.6.6
    
    (npy13) vlad:~/Projects/test$ python3 -c 'import ConfigSpace'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/vlad/Projects/test/npy13/lib/python3.5/site-packages/ConfigSpace/__init__.py", line 33, in <module>
        from ConfigSpace.configuration_space import Configuration, \
      File "ConfigSpace/configuration_space.py", line 37, in init ConfigSpace.configuration_space
      File "__init__.pxd", line 872, in init ConfigSpace.hyperparameters
    ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

Tried with 1.14.0:

    (tt) vlad:~/Projects/test$ pip3 freeze
    ConfigSpace==0.4.7
    Cython==0.29.3
    numpy==1.14.0
    pyparsing==2.3.1
    typing==3.6.6
    
    (tt) vlad:~/Projects/test$ python3 -c 'import ConfigSpace'
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/vlad/Projects/test/tt/lib/python3.5/site-packages/ConfigSpace/__init__.py", line 33, in <module>
    from ConfigSpace.configuration_space import Configuration, \
    File "ConfigSpace/configuration_space.py", line 37, in init ConfigSpace.configuration_space
    File "__init__.pxd", line 872, in init ConfigSpace.hyperparameters
    ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

And with 1.15.0:

    (npy15) vlad:~/Projects/test$ pip3 freeze
    ConfigSpace==0.4.7
    Cython==0.29.3
    numpy==1.15.0
    pyparsing==2.3.1
    typing==3.6.6
    
    (npy15) vlad:~/Projects/test$ python3 -c 'import ConfigSpace'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/vlad/Projects/test/npy15/lib/python3.5/site-packages/ConfigSpace/__init__.py", line 33, in <module>
        from ConfigSpace.configuration_space import Configuration, \
      File "ConfigSpace/configuration_space.py", line 37, in init ConfigSpace.configuration_space
      File "__init__.pxd", line 872, in init ConfigSpace.hyperparameters
    ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

But it works with 1.16.0:

    (npy16) vlad:~/Projects/test$ pip3 freeze
    ConfigSpace==0.4.7
    Cython==0.29.3
    numpy==1.16.0
    pyparsing==2.3.1
    typing==3.6.6

    (npy16) vlad:~/Projects/test$ python3 -c 'import ConfigSpace'
    (npy16) vlad:~/Projects/test$ echo $?
    0

I guess the install should fail if the dependencies aren't met. Would it be possible to enforce the required version of numpy?

**Comment by mfeurer** [comment]
Hey @vladvelici, I'm afraid that this is not directly an issue of the numpy version. To check this I added a few more numpy versions to the build matrix in #108 and they all work. Could you please provide a full installation example so I can reproduce this issue?

**Comment by vladvelici** [comment]
I've tried again on a different machine, Ubuntu 16.04, python 3.5, and I could not replicate the above. In the meantime I've update the machine I tried this initially from Ubuntu 16.04 to 18.04; now I can't replicate but it's running python 3.6 (and I don't have the old virtualenvs).

It's really strange. I posted this issue because simply updating numpy made my scripts that used ConfigSpace run fine. Then tried the virtualenv stuff I posted above and I thought it's a case of requirements not being strict enough. Now I'm just confused, it's likely there was something in my environment that was causing it but can't tell what.

What I did for the above was simply:

    # go to a test folder and for all versions I posted above
    virtualenv npy15
    source npy15/bin/activate
    pip3 install numpy==1.15.0
    pip3 install configspace
    python3 -m 'import ConfigSpace'

and it would crash as shown above unless installing numpy==1.16.0.

**Comment by mfeurer** [comment]
Closing this as numpy 1.16 is quite old and we're now at 1.18/1.19. Please reopen if this is still an issue in a clean installation.
