### ISSUE TITLE
ForbiddenInClause error when writing to JSON

### ISSUE THREAD

**Issue by ashraaghav** [automl/ConfigSpace#109]
When using ForbiddenInClause, I could not write the ConfigSpace object to JSON. It throws the following error:

`TypeError: Object of type 'set' is not JSON serializable`

Probably because the set is not being converted to a list during serialization? I don't face this error with an InCondition though.

Minimal reproducible example:

```
import ConfigSpace as CS
from ConfigSpace import hyperparameters as CSH
import ConfigSpace.read_and_write.json as CSjson

cs = CS.ConfigurationSpace()
A = CSH.UniformIntegerHyperparameter("A", 1, 10, default_value=1)
B = CSH.CategoricalHyperparameter("B", ['a', 'b', 'c'], default_value='a')
fc1 = CS.ForbiddenInClause(A, [2,3])
cs.add_forbidden_clause(fc1)

with open('./configspace.json', 'w') as fh:
    fh.write(CSjson.write(cs))

```

**Comment by mfeurer** [comment]
Please excuse this issue. It has actually been fixed but I forgot to push to pypi. Please re-install to make this work.
