### ISSUE TITLE
Hyperparameter floating point precision in configuration search space

### ISSUE THREAD

**Issue by mfeurer** [automl/ConfigSpace#11]
@hmendozap raised this issue in the auto-sklearn issue tracker:

When adding a `UniformFloat` or `Constant` hyperparameter to the configuration space of any component, the string conversion to the 'parameter configuration space file' has only 10 decimal digits precision that mismatches the native float precision (53 bits) when running auto-sklearn and setting the hyperparameter for a component.

I believe this is specific to the pcs writer of SMAC. @mlindauer is this a critical issue that we should fix?

**Comment by mlindauer** [comment]
So, this concerns only using SMAC2?

I would expect that in most cases 10 digits should be more than enough.

**Comment by mfeurer** [comment]
I assume it'll also concern SMAC3 since the io module is more or less the same. Nevertheless, I also don't see any practical implications of this. Shall I close it for now?

**Comment by mlindauer** [comment]
I think it would not hurt to fix this at some point,
but it is not crucial.
