### ISSUE TITLE
hyperparameter dependency

### ISSUE THREAD

**Issue by pinnnnnn** [automl/ConfigSpace#111]
Is there a way that I can specify the dependency of two hyperparameters?

For example I have two hyperparameters a and b, and I want the value of a always larger than b during the tuning process.

**Comment by mfeurer** [comment]
Currently, this is not implemented. If you are interested in adding this I can give you some advice.

**Comment by mhoangvslev** [comment]
Please make these advices public

**Comment by mfeurer** [comment]
Closing this as I added a better answer in #198. Please ping @mhoangvslev if you are still interested in adding this.
