### ISSUE TITLE
CategoricalHyperparameter with multiple choices

### ISSUE THREAD

**Issue by GeorgesAlkhouri** [automl/ConfigSpace#121]
Is there a possibility to create a categorical hyperparameter with multiple choices.

So for example:
```
# 3 choices
categorical_choices = [1,2,3]
probability_for_choices = [0.33, 0.33, 0.33]

multi_choice_hypterparameter(categorical_choices, probability_for_choices)

res = multi_choice_hypterparameter.sample_choices()

#res could be:

[1,1,0] --> 1,2
[0,1,0] --> 2
[0,0,0] --> 
#... and so on
```

This also would need a categorical one hot vector representation.
I am thinking about this because I'm doing some research with sequential Model-Based optimization (also Model-Based reinforcement learning) and need a complex configuration setup to tune an Entity Resolution System.

**Comment by mlindauer** [comment]
There is no such feature currently.

I wonder a bit why you want to specify the probabilities for each choice. Please note that a BO-tool (such as SMAC) will only return a single hyperparameter configuration and not a probability distribution over configurations.
Of course you can encode these categorical choices without probabilities by using an one-hot encoding:

```
choice1 categorical [0,1]
choice2 categorical [0,1]
choice3 categorical [0,1]
...
```

We always wanted to allow users to specify expert knowledge (e.g., in the form of probabilities) as a prior to guide BO. However, that is not implemented so far and I don't know whether that's actually what you plan for.

Cheers,
Marius

**Comment by GeorgesAlkhouri** [comment]
Thanks for the clear answer.
