### ISSUE TITLE
Is there a good way to implement 'shape' hyperparameter?

### ISSUE THREAD

**Issue by hgt312** [automl/ConfigSpace#122]
Is there a good way to implement 'shape' hyperparameter?
I just want to generate random shapes (tuples), with arguments ndim, lower and upper.

Or there is a sample/doc to help write a extension?

**Comment by mfeurer** [comment]
I'm not sure if I get your question. Do you want to sample the size of an array for numpy? If yes, you could use one integer hyperparameter for the number of dimensions, and one integer hyperparameter for each possible dimension, which would be conditional on the dimension hyperparameter.

**Comment by hgt312** [comment]
Yeah, but I want a tuple with different values (same is ok) on each position.

**Comment by mfeurer** [comment]
Would it be possible to convert the configuration into tuples in your application?

**Comment by hgt312** [comment]
Set a random seed, and use np.random.randint may be a solution

**Comment by mfeurer** [comment]
Closing this as #244 is a better explanation of the problem.
