### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by mitar** [automl/ConfigSpace#124]
Is there any preferred way to cite ConfigSpace in an academic setting?

**Comment by mfeurer** [comment]
Not yet. Until what time do you need this?

**Comment by mitar** [comment]
No worries, I will just cite the GitHub repo for now. Just wanted to make sure I haven't missed anything. :-)

**Comment by mfeurer** [comment]
Here we go https://arxiv.org/abs/1908.06756

**Comment by mlindauer** [comment]
@mfeurer maybe add it also to the readme (and/or docu)?

**Comment by mitar** [comment]
Thanks!

**Comment by mfeurer** [comment]
Thanks for the suggestion @mlindauer 

It's [here](https://github.com/automl/ConfigSpace#citing-the-configspace)
