### ISSUE TITLE
About the use of conditional parameters

### ISSUE THREAD

**Issue by 87302380** [automl/ConfigSpace#125]
Hello everyone，

I have a requirement, but I don't know how to use configspace to express.

Parameter A is a CategoricalHyperparameter. A have choices ['a', 'b']
when A = 'a'
Parameter B is a number with a value between 10 and 100, 
when A = 'b'
Parameter B is a number with a value between 100 and 200 , 

It sounds simple, but I don't know how to restrain them. 
I read the documentation but did not find a constraint on the different scope of the same parameter.

thank

**Comment by mfeurer** [comment]
Could you please check #113. I believe this is a duplicate and the solution is given there..
