### ISSUE TITLE
Renaming hyperparameter

### ISSUE THREAD

**Issue by janvanrijn** [automl/ConfigSpace#126]
Is it possible to rename a hyperparameter in the ConfigSpace?

One could imagine that a "base configuration" has vanilla hyperparmaters, but if it is wrapped in a pipeline all hyperparameters need to be prefixed with the appropriate prefix. 

If not possible, is it interesting if I were to create a PR on this?

**Comment by mfeurer** [comment]
Are you looking for [add_configuration_space](https://automl.github.io/ConfigSpace/master/API-Doc.html#ConfigSpace.configuration_space.ConfigurationSpace.add_configuration_space)?

**Comment by janvanrijn** [comment]
Nice, yes. 

I have solved it in the sklearn bot differently now, but might revisit this decision.
