### ISSUE TITLE
setup.py fails on system with ASCII default encoding

### ISSUE THREAD

**Issue by Jabb0** [automl/ConfigSpace#137]
Hello,
the pip install of ConfigSpace fails on systems with a default encoding not supporting the letter "ü".
This is due to the readfile of the "README" without an explicit encoding. 

As docker container per default use ASCII as their encoding this will not allow installing ConfigSpace inside such a container.
Suggestion: Please include encoding="utf-8" in every open() of a file.

    # Helper functions
    def read_file(fname):
        """Get contents of file from the modules directory"""
        return open(os.path.join(os.path.dirname(__file__), fname), encoding="utf-8").read()

Thank you!

**Comment by mfeurer** [comment]
Thanks a lot for the report. This is closed via #138 and will be fixed in the next release.
