### ISSUE TITLE
Problem UniformIntegerHyperparameter with quantization=2 and lower=1.

### ISSUE THREAD

**Issue by Eric2Hamel** [automl/ConfigSpace#140]
I am just started using ConfigSpace==0.4.11 with Ubuntu and python 3.7.5.

I have seen a strange behavior using the following code
```
import ConfigSpace as CS
import ConfigSpace.hyperparameters as CSH

config_space = CS.ConfigurationSpace(seed=1)
uniform_int_hp = CSH.UniformIntegerHyperparameter(name='unit_int', lower=1, upper=7, log=False, q=2)
config_space.add_hyperparameter(uniform_int_hp)
```

And using `config_space.sample_configuration()` multiple times I got the following results.
Configuration:
  unit_int, Value: 4
Configuration:
  unit_int, Value: 6
Configuration:
  unit_int, Value: 0
Configuration:
  unit_int, Value: 2
Configuration:
  unit_int, Value: 0

I was more expecting to have these values {1, 3, 5, 7} and not {0, 2, 4, 6}.

Have I tried with other quantization factors (3, 4) and the result were similar.

If it is the right result, how can I obtain a distribution that gives me those sampling values?

Thanks

**Comment by Eric2Hamel** [comment]
I have a similar problem with i

mport ConfigSpace as CS
import ConfigSpace.hyperparameters as CSH

config_space = CS.ConfigurationSpace(seed=1)
distribution = CSH.UniformFloatHyperparameter(name="uni_float", lower=1., upper=11., log=False, q=2.)                                                                               
config_space.add_hyperparameter(distribution)

Sampling multiple time with `config_space.sample_configuration()`, I obtained:
 2.0,
 1.0,
 4.0,
 4.0,
 8.0,
 1.0,
 2.0,
 1.0,
 2.0,
 8.0,
 4.0,
 4.0,
 6.0,
 11.0,
 10.0,

I was more expecting to have these values {1, 3, 5, 7, 9, 11} and not {1., 2., 4., 6., 8., 10., 11.}.
Which seems to have made a q factor of 2 between 2 and 10. and add the start and stop in the sampling.

**Comment by mfeurer** [comment]
Thanks for reporting this, this is indeed a bug. I just pushed a fix for the first issue to the master branch and will have a look at the floating point values after the weekend.

**Comment by mfeurer** [comment]
This is now part of the latest 0.4.12 release.
