### ISSUE TITLE
Probabilities get lost in CategoricalHyperparameter's copy function

### ISSUE THREAD

**Issue by mzeiseSAP** [automl/ConfigSpace#150]
During tests we noted that the probabilities of a categorical hyper-parameter are lost when it is used as a switch for sub-configuration spaces, It happens when `ConfigurationSpace.add_configuration_space()` is calling `CategoricalHyperparameter.__copy__()` which previously did not take over any defined probabilities/weights. PR #149 contains a fix as well as unit tests illustrating this issue.

**Comment by mfeurer** [comment]
Fixed by merging #149.
