### ISSUE TITLE
[Bug] TypeError: Choice 'None' is not supported

### ISSUE THREAD

**Issue by rohan-gt** [automl/ConfigSpace#159]
When I create a ConfigSpace with the choices `[None, 'balanced']` for the `class_weight` in `LogisticRegression` and pass it to BOHB, I get the following error: `TypeError: Choice 'None' is not supported`

**Comment by mfeurer** [comment]
Not allowing `None` is not a bug, but a safeguard, please see [this earlier issue](https://github.com/automl/ConfigSpace/issues/104). You would have to use a placeholder string and convert that back to `None` yourself.

**Comment by rohan-gt** [comment]
@mfeurer if I pass `'None'` instead of `None`, will ConfigSpace handle it?

**Comment by mfeurer** [comment]
Yes, that'll work. You can then check in your target algorithm:
```python
if hyperparameter_value == 'None':
    hyperparameter_value = None
```

**Comment by rohan-gt** [comment]
Thanks. An entry for the same in the documentation would be useful
