### ISSUE TITLE
Set float precision

### ISSUE THREAD

**Issue by jendrikseipp** [automl/ConfigSpace#160]
I have a float parameter `x` and I'm only interested in testing values up to a certain precision (for example `x=0.1, x=0.2, x=0.3, ..., x=100.0`, but not `x=0.15`. Is there any way to specify this apart from using a categorical parameter?

Maybe related to this: what is the `q` "quantization factor" that the docs mention?

**Comment by mzeiseSAP** [comment]
If I understand your problem correctly, the `q` argument is indeed what you are looking for:

```
import ConfigSpace as CS
import ConfigSpace.hyperparameters as CSH

cs = CS.ConfigurationSpace(seed=1234)
a = CSH.UniformFloatHyperparameter('a', lower=0, upper=1, q=0.1)
cs.add_hyperparameter(a)

for _ in range(5):
	print(cs.sample_configuration())
```

The output is then like this:
```
Configuration:
  a, Value: 0.2
Configuration:
  a, Value: 0.6000000000000001
Configuration:
  a, Value: 0.4
Configuration:
  a, Value: 0.8
Configuration:
  a, Value: 0.8
```

**Comment by jendrikseipp** [comment]
Perfect, thanks for the quick answer!

**Comment by mfeurer** [comment]
Thank's @mzeiseSAP for providing the answer. Another possibility would be using an `OrdinalHyperparameter`.
