### ISSUE TITLE
any of implementation for a single hyper parameter

### ISSUE THREAD

**Issue by tmeshorer** [automl/ConfigSpace#161]
Hi All,

Is there a way to implement "any of" sampling for a single hyperparameter? For example, in a decision tree the 
"max_features" hp, can have: int, float or {“auto”, “sqrt”, “log2”}, default=None

Hence, is there a way to define space for each possible option, and sample only from one of the spaces?

Thanks.

**Comment by mfeurer** [comment]
Unfortunately, we do not support this at the moment.

Closing this as a duplicate of #113.
