### ISSUE TITLE
Fix bdist_wheel

### ISSUE THREAD

**Issue by mfeurer** [automl/ConfigSpace#162]
Currently, the ConfigSpace fails on `python setup.py bdist_wheel`. This is so far not an issue as pip would then continue with `python setup.py install`. However, they are planning to remove this fallback as described here: https://github.com/pypa/pip/issues/8368

**Comment by Deathn0t** [comment]
Hello @mfeurer, Did you start working on this? The PyPI 21.0 is coming [next January ](https://pip.pypa.io/en/stable/development/release-process/#:~:text=Support%20for%20Python%202.7%20will,2021)%2C%20whichever%20is%20earlier.) and directly fail if the wheel is failing.

**Comment by mfeurer** [comment]
Hi, I think I have fixed that in https://github.com/automl/ConfigSpace/pull/163 Thanks for the reminder
