### ISSUE TITLE
No matter how I try to install ConfigSpace by whatever means either through installing autogluon or directly installing configspace 

### ISSUE THREAD

**Issue by AnthonyTheKoala** [automl/ConfigSpace#165]
I am having having problems installing ConfigSpace by whatever means, whether it is. Whether it is installing directly by pipping configspace or by pipping autogluon, no matter how ConfigSpace is installed whether directly installing ConfigSpace or indirectly where another package requires the installation requires the installation of ConfigSpace. 
**End result** I cannot get a successful installation of ConfigSpace.

Here is an example of an attempted install via msys64's mingw64 **OR** git bash window. The result is the same:
<pre>
C:\Python38>pip install ConfigSpace --upgrade --force --no-color
Collecting ConfigSpace
  Using cached ConfigSpace-0.4.15.tar.gz (964 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip' install
 --ignore-installed --no-user --prefix 'C:\Users\A\AppData\Local\Temp\pip-build-
env-c1vor2mj\overlay' --no-warn-script-location --no-binary :none: --only-binary
 :none: -i https://pypi.org/simple -- setuptools wheel numpy Cython
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\python38\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "c:\python38\lib\site-packages\pip\__main__.py", line 26, in 
      sys.exit(_main())
    File "c:\python38\lib\site-packages\pip\_internal\cli\main.py", line 73, in
main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "c:\python38\lib\site-packages\pip\_internal\commands\__init__.py", lin
e 104, in create_command
      module = importlib.import_module(module_path)
    File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "", line 1014, in _gcd_import
    File "", line 991, in _find_and_load
    File "", line 975, in _find_and_load_unlocked
    File "", line 671, in _load_unlocked
    File "", line 783, in exec_module
    File "", line 219, in _call_with_frames_removed

    File "c:\python38\lib\site-packages\pip\_internal\commands\install.py", line
 17, in 
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup

    File "c:\python38\lib\site-packages\pip\_internal\cli\req_command.py", line
16, in 
      from pip._internal.index.collector import LinkCollector
    File "c:\python38\lib\site-packages\pip\_internal\index\collector.py", line
14, in 
      from pip._vendor import html5lib, requests
    File "c:\python38\lib\site-packages\pip\_vendor\requests\__init__.py", line
125, in 
      from . import utils
    File "c:\python38\lib\site-packages\pip\_vendor\requests\utils.py", line 25,
 in 
      from . import certs
    File "c:\python38\lib\site-packages\pip\_vendor\requests\certs.py", line 15,
 in 
      from pip._vendor.certifi import where
    File "c:\python38\lib\site-packages\pip\_vendor\certifi\__init__.py", line 1
, in 
      from .core import contents, where
    File "c:\python38\lib\site-packages\pip\_vendor\certifi\core.py", line 12, i
n 
      from importlib.resources import path as get_path, read_text
    File "c:\python38\lib\importlib\resources.py", line 11, in 
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401

    File "c:\python38\lib\site-packages\typing.py", line 1359, in 
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "c:\python38\lib\site-packages\typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' 'c:\pyth
on38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Us
ers\A\AppData\Local\Temp\pip-build-env-c1vor2mj\overlay' --no-warn-script-locati
on --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setupto
ols wheel numpy Cython Check the logs for full command output.
</pre>
    "Check the logs for full command output" - where are they and what is their name please? I tried searching for .log, log.* to no avail.

    Are there any other things I must do?

Info:
OS: Win 7 - 64-bit
mysys64: mingw64, version 10.2.2
MSVC: CL version Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24234.1 for x64
Copyright (C) Microsoft Corporation. All rights reserved.
Python: v3.8.5 64-bit
numpy.version: '1.19.2'
cython.version: '0.29.21'
pyparsing.version:'2.4.7'

So if I am installing autogluon which uses configspace or trying to install configspace on its own, are there any actions to do?
I tried the path environment - no foreseeable problems.

Where are the supposed 'logs' mentioned on the error message?

Should I 'def' the python libraries because I noticed one time that the redeffed python dll files to lib files were larger than the lib files supplied by python.

Many thanks,
Anthony of Sydney

**Comment by mfeurer** [comment]
Thanks @AnthonyTheKoala for reporting this. I have never seen this issue, but also never worked on Windows.

The only thing I could find was this [SO thread](https://stackoverflow.com/a/58067012) which suggests that this is due to installing `typing` instead of using the built-in.

**Comment by AnthonyTheKoala** [comment]
Dear Matthias,
Thank you for your reply.
Unfortunately uninstalling 'typing' by
<pre>
pip uninstall typing
</pre>
did not remove the problem.
For your information the stackexchange thread also said to downgrade to v3.6 of python.
A co-ordinator from autogluon which uses configspace said the same to downgrade to v3.6 of python. 

**However ** I just transferred everything to v3.8.5 - a lot of bandwidth (eg tensorflow is 385MB was involved in downloading packages for v3.8.5 which is not compatible with v3.6. Hence I cannot simply copy files from v3.6's site-packages to v3.8.5.

Solution - I will wait until configspace becomes compatible with v3.8.5 Python.

Merci, danke, thank you,
Anthony of Sydney

**Comment by AnthonyTheKoala** [comment]
Dear Matthias,
I uninstalled typing then in my gitbash terminal, I installed by source. I got a different kind of errors.
<pre>
# installed by source
$ pip install .
Processing c:\python38\configspace-0.4.15
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: cython in c:\python38\lib\site-packages (from ConfigSpace==0.4.15) (0.29.21)
Requirement already satisfied: numpy in c:\python38\lib\site-packages (from ConfigSpace==0.4.15) (1.19.2)
Requirement already satisfied: pyparsing in c:\python38\lib\site-packages (from ConfigSpace==0.4.15) (2.4.7)
Building wheels for collected packages: ConfigSpace
  Building wheel for ConfigSpace (PEP 517): started
  Building wheel for ConfigSpace (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\A\AppData\Local\Temp\tmpfn6t8mcb'
       cwd: C:\Users\A\AppData\Local\Temp\pip-req-build-8xi89qom
  Complete output (52 lines):
  running bdist_wheel
  running build
  running build_py
  running build_ext
  skipping 'ConfigSpace\hyperparameters.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\forbidden.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\conditions.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\c_util.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\util.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\configuration_space.c' Cython extension (up-to-date)
  building 'ConfigSpace.hyperparameters' extension
  C:\msys64\mingw64\bin\gcc.exe -mdll -O -Wall -Ic:\python38\include -Ic:\python38\include -IC:\Users\A\AppData\Local\Temp\pip-build-env-s9m9nr_u\overlay\Lib\site-packages\numpy\core\include -c ConfigSpace\hyperparameters.c -o build\temp.win-amd64-3.8\Release\configspace\hyperparameters.o
  ConfigSpace\hyperparameters.c:201:41: warning: division by zero [-Wdiv-by-zero]
    201 |     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
        |                                         ^
  ConfigSpace\hyperparameters.c:201:12: error: enumerator value for '__pyx_check_sizeof_voidp' is not an integer constant
    201 |     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
        |            ^~~~~~~~~~~~~~~~~~~~~~~~
  In file included from C:\Users\A\AppData\Local\Temp\pip-build-env-s9m9nr_u\overlay\Lib\site-packages\numpy\core\include/numpy/ndarraytypes.h:4,
                   from C:\Users\A\AppData\Local\Temp\pip-build-env-s9m9nr_u\overlay\Lib\site-packages\numpy\core\include/numpy/ndarrayobject.h:12,
                   from C:\Users\A\AppData\Local\Temp\pip-build-env-s9m9nr_u\overlay\Lib\site-packages\numpy\core\include/numpy/arrayobject.h:4,
                   from ConfigSpace\hyperparameters.c:610:
  C:\Users\A\AppData\Local\Temp\pip-build-env-s9m9nr_u\overlay\Lib\site-packages\numpy\core\include/numpy/npy_common.h:168:20: warning: '_fseeki64' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
    168 | extern int __cdecl _fseeki64(FILE *, long long, int);
        |                    ^~~~~~~~~
  C:\Users\A\AppData\Local\Temp\pip-build-env-s9m9nr_u\overlay\Lib\site-packages\numpy\core\include/numpy/npy_common.h:169:26: warning: '_ftelli64' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
    169 | extern long long __cdecl _ftelli64(FILE *);
        |                          ^~~~~~~~~
  In file included from C:\Users\A\AppData\Local\Temp\pip-build-env-s9m9nr_u\overlay\Lib\site-packages\numpy\core\include/numpy/ndarraytypes.h:1822,
                   from C:\Users\A\AppData\Local\Temp\pip-build-env-s9m9nr_u\overlay\Lib\site-packages\numpy\core\include/numpy/ndarrayobject.h:12,
                   from C:\Users\A\AppData\Local\Temp\pip-build-env-s9m9nr_u\overlay\Lib\site-packages\numpy\core\include/numpy/arrayobject.h:4,
                   from ConfigSpace\hyperparameters.c:610:
  C:\Users\A\AppData\Local\Temp\pip-build-env-s9m9nr_u\overlay\Lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h:14:9: note: '#pragma message: C:\Users\A\AppData\Local\Temp\pip-build-env-s9m9nr_u\overlay\Lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION'
     14 | #pragma message(_WARN___LOC__"Using deprecated NumPy API, disable it with " \
        |         ^~~~~~~
  ConfigSpace\hyperparameters.c: In function '__Pyx_ImportType':
  ConfigSpace\hyperparameters.c:69807:13: warning: unknown conversion type character 'z' in format [-Wformat=]
  69807 |             "%s.%s size changed, may indicate binary incompatibility. "
        |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ConfigSpace\hyperparameters.c:69808:24: note: format string is defined here
  69808 |             "Expected %zd from C header, got %zd from PyObject",
        |                        ^
  ConfigSpace\hyperparameters.c:69807:13: warning: unknown conversion type character 'z' in format [-Wformat=]
  69807 |             "%s.%s size changed, may indicate binary incompatibility. "
        |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ConfigSpace\hyperparameters.c:69808:47: note: format string is defined here
  69808 |             "Expected %zd from C header, got %zd from PyObject",
        |                                               ^
  ConfigSpace\hyperparameters.c:69807:13: warning: too many arguments for format [-Wformat-extra-args]
  69807 |             "%s.%s size changed, may indicate binary incompatibility. "
        |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  error: command 'C:\\msys64\\mingw64\\bin\\gcc.exe' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ConfigSpace
Failed to build ConfigSpace
ERROR: Could not build wheels for ConfigSpace which use PEP 517 and cannot be installed directly
</pre>
Lots of warnings even when using the mingw64 gcc.

Merci, danke, thank you,
Anthony of Sydney

**Comment by mfeurer** [comment]
Thanks for trying these suggestions, it's very unfortunate that they don't work.

Regarding 3.8.5: we are testing against 3.8.5 in CI, see for example this recent build: https://travis-ci.org/github/automl/ConfigSpace/jobs/731777266

Regarding the 2nd error I don't understand what's going on here, and I've never seen such an issue. Is AutoGLUON officially supporting Windows? If yes, maybe one of the AutoGLUON maintainers can help here as they hopefully know how to compile it.

**Comment by AnthonyTheKoala** [comment]
I am cutting a long story very short.
This applies to the installation of ConfigSpace whether you are installing directly OR whether a package such as autogluon installs or tries to install the package.

* pip  20.3 has PEP 517 and won't let you install. It 'accuses' you having incompatible C++ parameters being overparameterized or the wrong size. So I downgraded pip to 18.1 in order to avoid the PEP 517 problem
<pre>
pip install --user pip==18.1
</pre>
This is a long story cut short.

* My python version is 3,8.6 - I have invested a lot of bandwidth (downloads) in downloading packages to 3.8.5.
*I have added the package line_profiler #So much to explain the reasoning of installing this.
<pre>
pip install line_profiler
</pre>
* I have installed MS Visual Studio 2019, not just the visual tools. 2019.
* The python's cygwincompiler.py had to be modified to accomodate versions of MS Visual Studio > MSVC 12
def get_msvcr():
<pre>
	# Using appropriate MS compiler
	# Adapted from https://bugs.python.org/file40608/patch.diff
  
	msc_pos = sys.version.find('MSC v.')
	
	if msc_pos != -1:
		msc_ver = sys.version[msc_pos+6:msc_pos+10]
		if msc_ver == '1600':
			return ['msvcr100']
		elif msc_ver >= '1900':
			# Visual Studio 2015 / Visual C++ 14.0
            # "msvcr140.dll no longer exists" http://blogs.msdn.com/b/vcblog/archive/2014/06/03/visual-studio-14-ctp.aspx
			return['msvcp140']; #try 'vcruntime140' or 'msvcp140'
		else:
			raise ValueError("Unknown MS Compiler version %s " % msc_ver)
</pre>
* Note for the above I did the above for another package pystan. I am avoiding anaconda and miniconda and tried to install from source - enough said. That is irrelevant for this.
* I had to modify the environment variable PATH to include amongst other packages c:\msys64\mingw64\bin and for python38's package - c:\users\whatever\AppData\Roaming\Python\Scripts.
* In other words if you thought the python38 environment variables path was c:\python38\scripts (say), for some inexplicable reason, you will find that the scripts which is also in c:\python38\scripts is also installed at c:\users\whatever\AppData\Roaming\Python\scripts and any compilation attempt may 'spew' if you don't include this additional path environment **EVEN IF ** you have installed in the path c:\python38\scripts.
<pre>
C:\Users\whatever\AppData\Roaming\Python\Scripts;C:\Windows\System32\WindowsPowerShell\v1.0;C:\swigwin-4.0.2;%mscvc_2019%\bin\Hostx64\x64;%msvc_2019%\include;%msvc_2019%\lib\x64 ;C:\msys64\mingw64\bin;C:\msys64\mingw64\include;C:\msys64\mingw64\lib;c:\python38;c:\python38\scripts;c:\python38\DLLs;c:\python38\Lib;c:\python38\libs;c:\python38\libs\python38.lib;;%graphviz_home%;%java_bin%;%java_include%;C:\windows\system32;c:\windows; 
</pre>
So far so good.
You may ask why install MSVC 2019/Visual Studio 2019?
Good question! When you boot up the IDLE package, you will see the MSVC version that the Python 3.8.6 was compiled.
<pre>
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
MS Visual Studio 2019's says MSVC v1927 and that is what you need as a C compiler.
</pre>
In addition you will want to install the the msvc runtimes by
<pre>
pip install --user msvc_runtime 
</pre>
* Note if you open the *.whl file using 7-zip (open as archive), you'll find that they are the *.dll files used in the MSVC runtime. * * * These *.dll files match the version of the MSVC 1927
* BUT not all msvc runtime dll files are the same size for a given name of the *.dll file even if they are v 1927! DON'T REPLACE THE DLL FILES FROM THE MSVC redistributables, otherwise your installation of whatever package will 'spew' out errors. So don't install that in the c:\python38 and c:\python38\scripts. USE THE dll files automatically installed from pipping the msvc_runtime.
Anyway, having said all that, you are on the way of installing ConfigSpace, BUT FOR a little thing.
<pre>
File "C:\Users\A\AppData\Local\Temp\pip-install-gi442ns7\numpy\numpy\distutils\mingw32ccompiler.py", line 564, in msvc_manifest_xml
          raise ValueError("Version %d,%d of MSVCRT not supported yet" %
      ValueError: Version 14,1 of MSVCRT not supported yet
</pre>
The important line is:
<pre>
      ValueError: Version 14,1 of MSVCRT not supported yet
</pre>
Conclusion , I will be patient and wait until ConfigSpace, is updated to handle the latest MSVC 2019.

Thank you,
Anthony of Sydney

**Comment by mfeurer** [comment]
I'm sorry to hear that the installation doesn't work. Unfortunately, no one in our group is using Windows nor knows how to develop for Windows and we therefore won't be able to debug or fix this. However, we'd be happy about any help we can get resolving this issue.

PS: the last error appears to be in numpy, not in ConfigSpace

**Comment by AnthonyTheKoala** [comment]
Dear Matthias,
Thank you for your reply.
My version of numpy is:
<pre>
import numpy
numpy.__version__
'1.19.2'
</pre>
To give it one more try, what is the minimum version of numpy please?
Thank you,
Anthony of Sydney

**Comment by mfeurer** [comment]
> To give it one more try, what is the minimum version of numpy please?

Unfortunately, I don't know. We don't have any test to check this and only test against the latest version.

**Comment by AnthonyTheKoala** [comment]
Dear Matthias,
Thank you for your reply.
Two bits of information:
(1) When I try to install configspace, the part of the installation advice is:
<pre>
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\A\AppData\Local\Temp\pip-build-env-60_z54dx\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel numpy Cython Check the logs for full command output.
</pre>
In the last statement where is the location of these "...logs for full command output..."?

(2) 
The version of numpy is:
<pre>
A@Anthony MINGW64 /c/python38
$ c:/python38/python.exe -c "import numpy;print(numpy.__version__)"
1.19.2
</pre>
I updated the latest version of numpy because other packages that I install update the numpy version. If I used a lower version of numpy it means that the installed package will not operate properly.

On the other hand, looking at the ConfigSpace "read the docs" the minimum requirement is Python >= 3.6.
For your information:
<pre>
OS: Win 7
Python: 3.8.5
Cython: 0.29.21`
Numpy: 1.19.2
Scipy: 1.5.3
msys64
* mingw64's gcc 10.2
* mingw32's gcc 10.2
</pre>

Again where are the location of the logs that are mentioned on the error message?

Thank you, danke, merci, gracias,
Anthony from Sydney

**Comment by maechler** [comment]
```
OS: macOS 10.15.7
Python: 3.8
```

I had a similar issue on mac using the Python version from Xcode: `/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python`

I could workaround it by installing and using the [official Python 3.8 release](https://www.python.org/downloads/mac-osx/).
