### ISSUE TITLE
Python 3.9.0 gcd import

### ISSUE THREAD

**Issue by sld** [automl/ConfigSpace#168]
Seems like need to change `from fractions import gcd` to `from math import gcd` for new python version.

```
~/.pyenv/versions/3.9.0/lib/python3.9/site-packages/ConfigSpace/nx/algorithms/dag.py in <module>
      1 # -*- coding: utf-8 -*-
----> 2 from fractions import gcd
      3
      4 import ConfigSpace.nx
      5

ImportError: cannot import name 'gcd' from 'fractions' (/home/dev/.pyenv/versions/3.9.0/lib/python3.9/fractions.py)
```

**Comment by eddiebergman** [comment]
Bumping, library doesn't specify Python 3.9 in setup.py but it would be a nice change so as to allow for using Python 3.9 with [autosklearn](https://github.com/automl/auto-sklearn).

Listed as deprecated since Python 3.5:
https://docs.python.org/3/whatsnew/3.9.html#removed

The reason being for anyone interested the issue and discussion of its change is at:
https://bugs.python.org/issue22486

**Comment by hadim** [comment]
Same here I am trying to build the package for py39 on conda forge and it fails because of that import: https://github.com/conda-forge/configspace-feedstock/pull/1

See also the doc: https://docs.python.org/3.5/library/fractions.html#fractions.gcd

**Comment by mfeurer** [comment]
Thanks a lot for reporting this. Would anyone like to do a PR fixing this (and adding Python3.9 to the build matrix)?

**Comment by eddiebergman** [comment]
@mfeurer I will give it a go tomorrow! :) 

Quick questions:
* Is the project similar in setup to [openml-python](https://github.com/openml/openml-python) for [testing](https://github.com/openml/openml-python/blob/develop/CONTRIBUTING.md) purposes?
* I'm not very familiar with CI systems, I assume this is just editing `.travis.yaml` and meta data in `setup.py`?

**Comment by mfeurer** [comment]
Cool, thanks @eddiebergman 

It was. This one still uses travis-ci, while we moved OpenML-Python to github actions recently. As far as I remember you need to change `.travis.yaml`, 'setup.py` and maybe the docs if they mention something about version support.

**Comment by eddiebergman** [comment]
Sorry, only got around to it today, there's a passing [merge request ](https://github.com/automl/ConfigSpace/pull/170) #170 whenever you have a chance to review it,

**Comment by mfeurer** [comment]
Thanks a lot @eddiebergman, this will be available in the upcoming release.
