### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by FedericoCeratto** [automl/ConfigSpace#169]
Hello,
ConfigSpace/read_and_write/pcs.py , pcs_new.py and json.py appear to be under GPL license and are being imported in the following files:
```
scripts/benchmark_sampling.py 
 
test/read_and_write/test_irace_writer.py 
test/read_and_write/test_pcs_converter.py 
test/read_and_write/test_pcs_converter.py 
test/read_and_write/test_json.py 
test/read_and_write/test_json.py 
test/read_and_write/test_json.py 
test/test_util.py 
test/test_converters_and_test_searchspaces/test_sample_configuration_spaces.py 
test/test_converters_and_test_searchspaces/test_sample_configuration_spaces.py 
```

The authors appear to be the same as the whole library, which is under BSD-3-Clause.
Should we consider the entire library to be under BSD-3-Clause?

**Comment by mfeurer** [comment]
Hi @FedericoCeratto,

Sorry, I didn't know that we still had files with the old GPL header in the library. They should never have been present and the library was always intended to be BSD-3-Clause. I have removed them and they are no longer present for v0.17.0. 

Please be aware that I'm not a lawyer and don't know whether the fact that the GPL header was there in the past has any influence on the library license.
