### ISSUE TITLE
Meta field is not copied when using `add_configuration_space`

### ISSUE THREAD

**Issue by mickare** [automl/ConfigSpace#176]
Hello,
the meta field of hyperparameters is not copied when calling `add_configuration_space`.
Greetings, mike

Expected: The meta field persists.
Actual: The meta field is None.

Offending lines:
- https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/hyperparameters.pyx#L224
- https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/hyperparameters.pyx#L354
- https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/hyperparameters.pyx#L727
- https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/hyperparameters.pyx#L1186
- https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/hyperparameters.pyx#L1398
- https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/hyperparameters.pyx#L1654

**Comment by mfeurer** [comment]
Thanks a lot for raising this issue and providing a fix!
