### ISSUE TITLE
NumPy warning when adding hyperparameters or using UniformIntegerHyperparameter

### ISSUE THREAD

**Issue by jeschment** [automl/ConfigSpace#179]
configSpace_warning.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
max_depth = UniformIntegerHyperparameter("max_depth", 1, 10, default_value=3)

Same warning together with the following one appears when using `add_hyperparameter()`:
configSpace_warning.py:7: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  cs.add_hyperparameter(max_depth)

**Comment by mfeurer** [comment]
Fixed via #183.
