### ISSUE TITLE
Getting an equivalent space to hyperopt

### ISSUE THREAD

**Issue by sergeyf** [automl/ConfigSpace#189]
Hello,

Thanks for this nice package and all the hard work on it. 

I am doing some benchmarking https://github.com/sergeyf/SmallDataBenchmarks) comparing `hyperopt` to `hpbandster-sklearn` on about ~100 datasets, and I'd like to make sure that I'm comparing apples to apples. I'm having a tough time making an equivalent hyperparameter space and I was hoping someone here could offer some brief guidance.

Here is my hyperopt space:

```python
from hyperopt import hp
from hyperopt.pyll import scope

HYPEROPT_SPACE = {
    "learning_rate": hp.choice("learning_rate", [0.1, 0.05, 0.01, 0.005, 0.001]),
    "num_leaves": scope.int(2 ** hp.quniform("num_leaves", 2, 7, 1)),  # sampling integers then doing 2 ** i
    "colsample_bytree": hp.quniform("colsample_bytree", 0.4, 1, 0.1),
    "subsample": hp.quniform("subsample", 0.4, 1, 0.1),
    "min_child_samples": scope.int(2 ** hp.quniform("min_child_samples", 0, 7, 1)),  # sampling integers then doing 2 ** i
    "min_child_weight": 10 ** hp.quniform("min_child_weight", -6, 0, 1),  # sampling integers then doing 10 ** i
    "reg_alpha": hp.choice("reg_alpha", [0, 10 ** hp.quniform("reg_alpha_pos", -6, 1, 1)]),  # 0 is tacked on
    "reg_lambda": hp.choice("reg_lambda", [0, 10 ** hp.quniform("reg_lambda_pos", -6, 1, 1)]),  # 0 is tacked on
    "max_depth": scope.int(hp.choice("max_depth", [-1, 2 ** hp.quniform("max_depth_pos", 1, 4, 1)])),  # -1 is tacked on
}
```

And here is my attempt to mimic this with `ConfigSpace`:

```python
import ConfigSpace as CS
import ConfigSpace.hyperparameters as CSH

HPBANDSTER_SPACE = CS.ConfigurationSpace(seed=0)
learning_rate = CSH.CategoricalHyperparameter(name="learning_rate", choices=[0.1, 0.05, 0.01, 0.005, 0.001])
num_leaves = CSH.UniformIntegerHyperparameter(name="num_leaves", lower=2 ** 2, upper=2 ** 7, log=True)
colsample_bytree = CSH.UniformFloatHyperparameter(name="colsample_bytree", lower=0.4, upper=1, q=0.1)
subsample = CSH.UniformFloatHyperparameter(name="subsample", lower=0.4, upper=1, q=0.1)
min_child_samples = CSH.UniformIntegerHyperparameter(name="min_child_samples", lower=2 ** 0, upper=2 ** 7, log=True)
min_child_weight = CSH.UniformFloatHyperparameter(name="min_child_weight", lower=10 ** -6, upper=10 ** 0, log=True)
reg_alpha = CSH.UniformFloatHyperparameter(name="reg_alpha", lower=10 ** -6, upper=10 ** 0, log=True)
reg_lambda = CSH.UniformFloatHyperparameter(name="reg_lambda", lower=10 ** -6, upper=10 ** 0, log=True)
max_depth = CSH.UniformIntegerHyperparameter(name="max_depth", lower=2 ** 1, upper=2 ** 5, log=True)
HPBANDSTER_SPACE.add_hyperparameters(
    [
        learning_rate,
        num_leaves,
        colsample_bytree,
        subsample,
        min_child_samples,
        min_child_weight,
        reg_alpha,
        reg_lambda,
        max_depth,
    ]
)
```

Some challenges:
- `hyperopt` can nest with `hp.choice("reg_alpha", [0, 10 ** hp.quniform("reg_alpha_pos", -6, 1, 1)])`. How can add just a choice of `0` with CS?
- With `hyperopt` I can do things like `10 ** hp.quniform("min_child_weight", -6, 0, 1)`. Is there an equivalent with CS? `CSH.UniformFloatHyperparameter(name="min_child_weight", lower=10 ** -6, upper=10 ** 0, log=True)` this isn't right because I need only 7 values instead of the whole range.

Thank you.

**Comment by mfeurer** [comment]
Hi @sergeyf, some suggestions on how to simplify things a bit to make them easier to compare:

* You can use hyperopt's `qloguniform` to get integers on a log scale.
* The configspace has `CSH.UniformIntegerHyperparameter` that accepts `log=True` and should then give the desired behavior.
* You can use [conditional hyperparameters](https://automl.github.io/ConfigSpace/master/User-Guide.html#nd-example-categorical-hyperparameters-and-conditions) to add the choice of `0`.

**Comment by mfeurer** [comment]
Closing this as there was no follow-up question. Please reopen if you have any further questions.
