### ISSUE TITLE
GPL-3.0 licensed file

### ISSUE THREAD

**Issue by tapdiego-amzn** [automl/ConfigSpace#190]
https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/read_and_write/irace.py has a GPL-3.0 license header. This does not seem to agree with the BSD-3-Clause license covering the rest of the package. Maybe a leftover from a previous version?

Related issue: https://github.com/automl/ConfigSpace/issues/169

**Comment by mfeurer** [comment]
Thanks a lot for notifying us @tapdiego-amzn, I just pushed a new commit and the change will be available in the next release.

**Comment by tapdiego-amzn** [comment]
Thank you very much!
