### ISSUE TITLE
Errors in reading non-string values from pcs file to Forbidden Clauses

### ISSUE THREAD

**Issue by dengdifan** [automl/ConfigSpace#193]
This is a similar issue to #110 and discovered in https://github.com/automl/SMAC3/issues/770. When reading a ConfigurationSpace with forbidden caluse from a pcs file, the read value (with type string) cannot be transformed adaptively to the required data type:

https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/read_and_write/pcs_new.py#L420

we could first check the type of hyperparameters and then transform the values accordingly before generating a new ForbiddenEqualsClause?

**Comment by mfeurer** [comment]
That would be great. Would you like to create a pull request for this behavior?

**Comment by mfeurer** [comment]
Closed via #247
