### ISSUE TITLE
OrdinalHyperparameters

### ISSUE THREAD

**Issue by ibrahimsaggaf** [automl/ConfigSpace#201]
For the OrdinalHyperparameters, are it's values have the same probability to be selected?
Thanks

**Comment by mfeurer** [comment]
A bounded uniform distribution, please see the code: https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/hyperparameters.pyx#L1850

**Comment by mfeurer** [comment]
Closing this as this is answered.
