### ISSUE TITLE
Definition of Equality between two configs

### ISSUE THREAD

**Issue by eddiebergman** [automl/ConfigSpace#204]
The Equality between two configs is [defined here](https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/configuration_space.pyx#L1551)

Two configs are deemed equal if:
* They have the same configuration values, as expected
* The come from the same config space.

Is this second requirement strictly necessary?

**Comment by mfeurer** [comment]
Yes, I think so. For example if we have two 2d search space, think Branin and Rosenbrock 2d. There can be configurations that are equal in the original space, but unequal after their transformation into the unit hypercube, which is for example done by SMAC.

Is there a use case where this is an issue?

**Comment by eddiebergman** [comment]
Nope no issue, just a question but that makes sense given the transformation. Ideally I would think a config has no dependency on the space it was made from but I understand why.
