### ISSUE TITLE
Manually setting an value of a key of a Config through `__setitem__` invalidates it's `_values`

### ISSUE THREAD

**Issue by eddiebergman** [automl/ConfigSpace#205]
It does not seem to make sense that manually setting an item with `config[key] = value` should delete the entire attribute `self._values`. Looking through the rest of the code, it seems like this would break a lot of functionality.

**Comment by mfeurer** [comment]
> Looking through the rest of the code, it seems like this would break a lot of functionality.

Could you please provide further details here? I don't think we had any issues on this end yet.

**Comment by eddiebergman** [comment]
Just to document, after our discussion, we had a thought to make `Configuration` objects immutable to saveon validation time as we can guarantee validaty at construction time, rather than everytime it's queried.
