### ISSUE TITLE
Potential speed improvements

### ISSUE THREAD

**Issue by mfeurer** [automl/ConfigSpace#206]
This issue lists potential speed improvements to keep track of them. There is no plan to implement them right now, but if you would like to contribute to ConfigSpace by doing so, please let us know:

# get_one_exchange_neighborhood

* `Generator` is not available in Cython, so this is a regular Python function
* To speed up this function it should be ported to Cython and all variables should be annotated
* To do so we need to implement a stateful class that implements the iterator protocol

# Collections

* We currently use Python collections in Cython code (sets, lists, deques)
* These create a non-negligible overhead
* replace them with [custom C-based collections](https://cython.readthedocs.io/en/latest/src/tutorial/clibraries.html) or use the [C-API](https://stackoverflow.com/questions/43553763/cythonize-list-of-all-splits-of-a-string/43557675#43557675) or the [C++ collections](https://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html).

# _transform_scalar and _transform_vector

* These are internal functions to transform between the unit representation and the real-world representation
* Check whether we need both versions and whether we can use a single one only and improve it's typing.

**Comment by eddiebergman** [comment]
Closed by #346
