### ISSUE TITLE
Inconsistent rounding prinicple between Integral Hyperparameters and conditions results in invalid configuration

### ISSUE THREAD

**Issue by dengdifan** [automl/ConfigSpace#216]
When combining Integral hyperparameter and conditions, sometimes it might result in an invalid configuration:
```
from ConfigSpace import Configuration, ConfigurationSpace, GreaterThanCondition
from ConfigSpace import UniformIntegerHyperparameter
import ConfigSpace

num_layer = UniformIntegerHyperparameter('num_layer', 1, 15, 3)
n_unit_6 = UniformIntegerHyperparameter('n_unit_4', 1, 10, 3)

cs = ConfigurationSpace()
cs.add_hyperparameters([num_layer, n_unit_6])
cond = GreaterThanCondition(n_unit_6, num_layer, 3)
cs.add_condition(cond)

cfg = cs.get_default_configuration()
array = cfg.get_array().copy()

idx = cs.get_idx_by_hyperparameter_name(num_layer.name)

new_value = 0.16666622459888458
new_array = ConfigSpace.c_util.change_hp_value(
    cs,
    array.copy(),
    num_layer.name,
    new_value,
    idx
)
cfg_new = Configuration(configuration_space=cs, vector=new_array)
print(cfg_new)
```
and we have 
```
  n_unit_4, Value: 3
  num_layer, Value: 3
```

instead of 
```
 num_layer, Value: 3
```

 Integral Hyperparameters generates a new configuration by rounding a  float value (e.g., if the transformed new value is 3.1, then it will be rounded to 3)
However, conditions only check if the new_value exceeds the integral value (e.g., the transformed new value is 3.1 > 3 passes the condition and generate an invalid  configuration)

Either we could check the parent HP's type before transforming the condition's ```vector_values``` :https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/conditions.pyx#L444
 or rewrite the Integral HPs to round the value with ```int```.

**Comment by eddiebergman** [comment]
We've decided to classify this as an internal function, and attempting to modify values directly in vectorized space is considered undefined behaviour.

The suggested alternative if you need to change hp's is to create a new `Configuration` directly with the values required.

If someone needs this function to exists externally, please do let us know!
