### ISSUE TITLE
Conduct documentation link checks on build

### ISSUE THREAD

**Issue by mfeurer** [automl/ConfigSpace#234]
Similar to https://github.com/automl/auto-sklearn/pull/1152

**Comment by eddiebergman** [comment]
Done now using `mkdocs` here: https://github.com/automl/ConfigSpace/blob/e03e2604ff6d5e485c7ccb30aa1905e51b7eaedb/.github/workflows/docs.yml#L27

Normally it's a warning but I've set it to strict mode in the checks
