### ISSUE TITLE
Create tag of repo for python 2 support

### ISSUE THREAD

**Issue by elibol** [automl/ConfigSpace#24]
Would it be possible to create a tag of this repository of the revision which is python 2 compatible? Ideally, this would be a version compatible with the python 2 compatible revision of autosklearn.

**Comment by elibol** [comment]
Is revision `4dcd54522c98c4b3416b56e70b3fecf2e4753398` stable for getting this code running with `auto-sklearn==0.1.0`?

**Comment by mfeurer** [comment]
I think that commit is stable and would work with auto-sklearn and python2.7.
