### ISSUE TITLE
Expected equality after pcs-write/read?

### ISSUE THREAD

**Issue by shukon** [automl/ConfigSpace#25]
I stumbled over the following and I wondered whether this is expected behaviour:
When I write a ConfigSpace-object to a file using the `pcs.write()` and load it again with `pcs.read()`, `cs == cs_reloaded` evaluates to `False`. From some debugging I get that the attributes `_idx_to_hyperparameter`, `_parents` and `_hyperparameter_idx` are responsible (possibly others too).
I am not very familiar with the ConfigSpace-class, but intuitively this feels like a bug rather than a feature.

**Comment by mfeurer** [comment]
This is certainly not intended. Is it possible for you to track the error down further or provide a minimal working/failing example?

**Comment by shukon** [comment]
So, a minimum example using the spear-params-mixed.pcs (https://github.com/automl/ConfigSpace/blob/master/test/test_searchspaces/spear-params-mixed.pcs):

```
>>> import ConfigSpace
>>> import ConfigSpace.io.pcs as pcs
>>> with open("spear-params-mixed.pcs", 'r') as f: cs_one = pcs.read(f.readlines())
... 
>>> with open("example.pcs", 'w') as f: f.write(pcs.write(cs_one))
... 
1753
>>> with open("example.pcs", 'r') as f: cs_two = pcs.read(f.readlines())
... 
>>> repr(cs_one) == repr(cs_two)
True
>>> cs_one == cs_two
False
```

From the equality test of the `ConfigSpace` (https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/configuration_space.py#L641-L649), elements of `__dict__` are compared. Investigating this, the following attributes seem to be responsible (except for random, which is already ruled out from equality-test):

```
>>> for attr in cs_one.__dict__:
...     if not getattr(cs_one, attr) == getattr(cs_two, attr):
...         print(attr)
... 
_hyperparameters
_conditionsals
_hyperparameter_idx
_idx_to_hyperparameter
_children
_parents
random
```

**Comment by mfeurer** [comment]
@shukon I just pushed a potential fix, could you please check it?

**Comment by shukon** [comment]
@mfeurer Two attributes remain problematic:
```
>>> for attr in cs_one.__dict__:
...     if not getattr(cs_one, attr) == getattr(cs_two, attr):
...         print(attr)
... 
_children
_parents
random
```

For `_parents` this is solely attributed to the order:
```
>>> print(cs_one._parents == cs_two._parents)
False
>>> print(dict(cs_one._parents) == dict(cs_two._parents))
True
```

For `_children` this is also attributed to the order of `_children` itself, but also the order of `_children['__HPOlib_configuration_space_root__']`:
```
>>> print(cs_one._children == cs_two._children)
False
>>> print(dict(cs_one._children) == dict(cs_two._children))
False
# Order without "HPO..."
>>> cs_one._children.pop('__HPOlib_configuration_space_root__')
>>> cs_two._children.pop('__HPOlib_configuration_space_root__')
>>> print(cs_one._children == cs_two._children)
False
>>> print(dict(cs_one._children) == dict(cs_two._children))
True
# Order of "HPO..."
>>> print(cs_one._children['__HPOlib_configuration_space_root__'] == cs_two._children['__HPOlib_configuration_space_root__'])
False
>>> print(dict(cs_one._children['__HPOlib_configuration_space_root__']) == dict(cs_two._children['__HPOlib_configuration_space_root__']))
True
```

**Comment by mfeurer** [comment]
@shukon could you please confirm that #51 fixes this bug?

**Comment by shukon** [comment]
@mfeurer , works now, thanks!
