### ISSUE TITLE
numpy and scipy as requirement?

### ISSUE THREAD

**Issue by dwoiwode** [automl/ConfigSpace#257]
Hi, I just installed ConfigSpace and realized that it requires scipy as dependency. I wondered where this package might need scipy but could not find anything in the code. Further I realized that not even numpy is imported outside of the tests.

As I like to keep my projects as slim as possible, I would propose to remove scipy and numpy from the general dependencies as they are not really needed for a configspace holder.

**Comment by mfeurer** [comment]
Hey, we use the `scipy.stats` module to access common distributions, such as the truncated normal or the beta distribution in the [hyperparameters module](https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/hyperparameters.pyx). Therefore, unfortunately, we cannot remove scipy from the dependency list.

**Comment by dwoiwode** [comment]
Hm okay, looks like I missed this part. Thank you for your response!
