### ISSUE TITLE
Generate number of layers and nodes of the neural network

### ISSUE THREAD

**Issue by lmhHydropower** [automl/ConfigSpace#278]
How to generate a list that represents the number of layers and nodes of the neural network?

For example, [32, 64, 32, 1] represents a network that has 4 layers with 32, 64, 32, 1 node, respectively.

**Comment by eddiebergman** [comment]
Hi @lmhHydropower,

I would represent this personally as:

```python
from ConfigSpace import ConfigurationSpace

cs = ConfigurationSpace({
    "layer1": [16, 32, 64],
    "layer2": [16, 32, 64],
    "layer3": [16, 32, 64],
    "output": 1
})

cs.sample_configuration()
```

There could be other ways, for example using a Normal distribution over some values you think are good and explicitly saying that the categorical choices are `ordinal`, i.e. it's a choice between things that are ordered.

```python
from ConfigSpace import ConfigurationSpace, Integer, Normal, Categorical

cs = ConfigurationSpace({
    "layer1": Integer("layer1", (8, 128), distribution=Normal(mu=32, sigma=16)),
    "layer2": Integer("layer2", (8, 128), distribution=Normal(64, 16)),
    "layer3": Categorical("layer3", [16, 32, 64, 128], ordered=True, default=32),
    "output": 1
})

cs.sample_configuration()
```

However if your delving into the world of finding neural architectures, aptly named Neural Architecture Search (NAS), then I highly recommend checking out NASlib which @Neonkraft is maintaining :)
