### ISSUE TITLE
[Question] Curious Why VSCode IntelliSense is not working on ConfigSpace

### ISSUE THREAD

**Issue by zhiruiluo** [automl/ConfigSpace#281]
Please pardon my stupid question. 
The ConfigSpace is all typed, but why VS Code IntelliSense doesn't work on it.

**Comment by eddiebergman** [comment]
Hi @zhiruiluo,

Yeah this is just an unfortunate reality of using `.pyc` files, i.e. using Cython. It's compiled to C and distributed as a binary wheel when you did `pip install` and so language servers that provide this "intellisense" (like VSCodes Pylance) can not inspect it for types.

I tried a few months ago to make it a bit easier by at least providing convenience functions for creating paramters using the newer `Float`, `Integer` and `Categorical` functions which create the hyperparameters for you. Using `Pyright` (base layer of Pylance) as a langauge server, it correctly gives me documentation and allows me to jump to source on these functions, so it's a start, but clearly when interacting with the `ConfigurationSpace` itself, you lack these smart abilities.

So what's the solution:
* One option considered was exporting `.pyi` files, these are type stubs that language servers can use. It won't give you the implementations, but at least the function signatures. The downside to this is then we have to keep these up to date too.
* The other solution is essentially just to migrate back away from `Cython`. The core reason to do so was to do with some efficiency of sampling many configurations from large complex spaces but there are many places in the code in which efficiency could be improved and I believe changing everything to `Cython` was a bit too much. At the very least, the complex operations could remain in `Cython` and move the main API points back to regular python.

I don't have much time for this at the moment though, sorry to say. I've been asked a few times and the changes likely require a concentrated effort to make sure we do not break anything and to properly benchmark functionality.

Best,
Eddie

**Comment by zhiruiluo** [comment]
Thanks @eddiebergman,

Thanks to that this repo has a well documented APIs, I have no problem learning from the documentation and build my project from it. I think type hint is a highly demanded feature for Python applicaitons. Cython is kinda new to me, but I will try to help on improving this later. 

Best,
Bill
