### ISSUE TITLE
Module name is not PEP8 compliant

### ISSUE THREAD

**Issue by sfalkner** [automl/ConfigSpace#3]
From PEP 8:

>  Package and Module Names
> 
> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

Does that mean the module should be 'configspace' rather than 'ConfigSpace'?

**Comment by mfeurer** [comment]
Yes, but I don't think I will fix this. Would you volunteer doing that ;) ?
