### ISSUE TITLE
Cannot import name duplicates_everseen

### ISSUE THREAD

**Issue by phsamuel** [automl/ConfigSpace#303]
Hello, I'm new to configspace. I tried to install it with pip install

> pip install ConfigSpace

The installation didn't give any warning. But when I try to import it, I got

> >>> import ConfigSpace
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/phsamuel/p3/lib/python3.8/site-packages/ConfigSpace/__init__.py", line 32, in <module>
>     from ConfigSpace.api import (Beta, Categorical, Distribution, Float, Integer,
>   File "/home/phsamuel/p3/lib/python3.8/site-packages/ConfigSpace/api/__init__.py", line 2, in <module>
>     import ConfigSpace.api.types as types
>   File "/home/phsamuel/p3/lib/python3.8/site-packages/ConfigSpace/api/types/__init__.py", line 1, in <module>
>     from ConfigSpace.api.types.categorical import Categorical
>   File "/home/phsamuel/p3/lib/python3.8/site-packages/ConfigSpace/api/types/categorical.py", line 8, in <module>
>     from ConfigSpace.hyperparameters import (CategoricalHyperparameter,
>   File "ConfigSpace/hyperparameters.pyx", line 34, in init ConfigSpace.hyperparameters
> ImportError: cannot import name duplicates_everseen
> 

I am using Ubuntu 22.04. But I tried 20.04 also and I got the same problem. I'm using virtualenv. I wonder if that may be the problem.

**Comment by eddiebergman** [comment]
Did you install `ConfigSpace` into you virtual environment? The function `duplicates_everseen` come from the `more_itertools` package which is listed as a requirement for the package.

[`setup.py` from the `0.6.1` release](https://github.com/automl/ConfigSpace/blob/88051ebb7c34b6c8e69777c75dbcbc120b7720fd/setup.py#L63).

You can diagnose if you have this installed with `pip list`

**Comment by phsamuel** [comment]
Thank you for the prompt reply! Yes, more_itertools was installed but it probably is conflicted with some system python packages. I created a virtualenv with `virtualenv --system-site-packages foo` earlier. Creating a new virtualenv without `--system-site-packages` resolve the conflict.
