### ISSUE TITLE
[Bug] Hyperparameters can set illegal default values when log=True

### ISSUE THREAD

**Issue by Neonkraft** [automl/ConfigSpace#330]
The following code crashes, because `NormalFloatHyperparameter` attempts to set a default value without respecting the bounds.

```
cs = ConfigurationSpace(
    name="myspace",
    space={
        "a": Float("a", bounds=(1, 2), distribution=Normal(1, 0), log=True),
    },
)
```

I've observed the same problem with `{Normal/Beta}{Float/Integer}Hyperparameter`.

**Comment by eddiebergman** [comment]
This example seems fixed in #346! Will hopefully be released next week :)
