### ISSUE TITLE
Illegal value for the frequent floating precision issue

### ISSUE THREAD

**Issue by nabenabe0928** [automl/ConfigSpace#333]
[Well-known precision issue](https://floating-point-gui.de/errors/comparison/)

Would you be able to use `np.isclose` or something similar for the comparison?
I think the problem came from [here](https://github.com/automl/ConfigSpace/blob/main/ConfigSpace/hyperparameters/uniform_float.pyx#L104-L110).

```python
In [1]: import ConfigSpace as CS

In [2]: config_space = CS.ConfigurationSpace()

In [3]: config_space.add_hyperparameter(CS.UniformFloatHyperparameter("a", 0.0, 1.0))
Out[3]: a, Type: UniformFloat, Range: [0.0, 1.0], Default: 0.5

In [4]: CS.Configuration(config_space, {"a": 1.0 + 1e-12})
---------------------------------------------------------------------------
IllegalValueError                         Traceback (most recent call last)
Cell In[4], line 1
----> 1 CS.Configuration(config_space, {"a": 1.0 + 1e-12})

File ~/anaconda3/envs/config-space/lib/python3.9/site-packages/ConfigSpace/configuration.py:90, in Configuration.__init__(self, configuration_space, values, vector, allow_inactive_with_values, origin, config_id)
     87     continue
     89 if not hp.is_legal(value):
---> 90     raise IllegalValueError(hp, value)
     92 # Truncate the float to be of constant length for a python version
     93 if isinstance(hp, FloatHyperparameter):

IllegalValueError: Value 1.000000000001: (<class 'float'>) is not allowed for hyperparameter a, Type: UniformFloat, Range: [0.0, 1.0], Default: 0.5
```

**Comment by eddiebergman** [comment]
Hmmm, while in principal I agree, it opens the door for what is `close`, i.e. should all `Float` parameters then also accept a tolerance?

**Comment by nabenabe0928** [comment]
In my use case, i.e. YAHPO, I just use the np.isclose with the default tolerance and if it's slightly out of the range, I clip the value.
Ofc, you cannot easily define what "close" means, but some packages seem to be affected by sampling from boundaries.
In that sense, all float parameters need to be (somehow) modified (optionally with warning).

**Comment by eddiebergman** [comment]
Just revisited this after finisihng #346. I think there's too many places where this `isclose` check would introduce difficulties in value space. However we do make use of `isclose` in vectorized space.

I'll close this with the statement that numbers provided in value space (as opposed to vectorized space) are given by the user and as such have the ability to choose their tolerance and what they'd like to do. However if you encounter issues like this in vectorized space, then please do raise another issue!
