### ISSUE TITLE
Bound for an Integer parameter depending on the value of another parameter?

### ISSUE THREAD

**Issue by mdorier** [automl/ConfigSpace#368]
Is there a way to have a configuration space like the following:
- Parameter "x" is defined as `Integer("x", (1, N))` (where `N` is a constant)
- Parameter "y" must be drawn uniformly within `(1, x)` once `x` has been drawn

**Comment by eddiebergman** [comment]
Yup, take a look [`LessThanCondition`](https://automl.github.io/ConfigSpace/latest/api/ConfigSpace/conditions/#ConfigSpace.conditions.LessThanCondition), definitely supported :)

Feel free to close if this is what you were looking for

**Comment by mdorier** [comment]
Maybe I didn't explain correctly (or I'm missing something about LessThanCondition). LessThanCondition would be useful to disable a parameter if another parameter exceeds a certain value, but that's not what I'm trying to do here.

What I'm trying to do is, for instance, the following:
- x should be drawn in [0, 100]
- y should be drawn in [0, x]
So for example ConfigSpace would sample x = 65, then sample y in [0, 65]. In another sample, it would sample x = 34 and sample y in [0, 34] accordingly.

How can I do that?

**Comment by eddiebergman** [comment]
Ahh apologies, [`ForbiddenGreaterThanRelation`](https://automl.github.io/ConfigSpace/latest/api/ConfigSpace/forbidden/#ConfigSpace.forbidden.ForbiddenGreaterThanRelation) is what you need then.

Essentially you can imagine these as checks that are required to be passed for a configuration to be sampled and valid.

```python
from ConfigSpace import ConfigurationSpace, ForbiddenGreaterThanRelation

cs = ConfigurationSpace({"x": (0, 100), "y": (0, 100)})
cs.add(ForbiddenGreaterThanRelation(cs["y"], cs["x"]))

samples = cs.sample_configuration(10)

for sample in samples:
    print(sample["x"], sample["y"])

```

The full list of Forbidden's are found here: https://automl.github.io/ConfigSpace/latest/reference/forbiddens/

**Comment by mdorier** [comment]
Ah excellent, thanks!
