### ISSUE TITLE
Configuration.__contains__ does not work (infinite recursion)

### ISSUE THREAD

**Issue by mdorier** [automl/ConfigSpace#378]
Here:

https://github.com/automl/ConfigSpace/blob/b7e62e3aceb1b22071bc14eca06b12745952b67a/src/ConfigSpace/configuration.py#L180

This makes the Configuration object call `__contains__` on itself, causing infinite recursion.

**Comment by eddiebergman** [comment]
Thanks again for all the reports! Should have been checking in `self.config_space`, not `self`. Test added to make sure it's caught.

Version `v1.1.1` already released on PyPI
