### ISSUE TITLE
Constants of type string do not work (sample_configutation returns the first letter of the string)

### ISSUE THREAD

**Issue by mdorier** [automl/ConfigSpace#379]
Example:

```
>>> from ConfigSpace import ConfigurationSpace, Constant
>>> const = Constant("const", "something")
>>> const
Constant(name='const', default_value='something', meta=None, size=1, value='something')
>>> cs = ConfigurationSpace()
>>> cs.add(const)
>>> cs
Configuration space object:
  Hyperparameters:
    const, Type: Constant, Value: something

>>> cs.sample_configuration()
Configuration(values={
  'const': 's',
})
```

**Comment by eddiebergman** [comment]
Thanks for all the reports! Very useful after the major release :)

This was fixed and released yesterday with #375, reported in #374 and release already with [Version 1.1](https://github.com/automl/ConfigSpace/blob/main/changelog.md#version-110)

Closing for now as this now works (fyi your repro `Constant` doesn't seem correct?). They don't have `default_value`, `size` or things of that manner
