### ISSUE TITLE
Stricter checking of brackets for conditional values in the new configspace format

### ISSUE THREAD

**Issue by mfeurer** [automl/ConfigSpace#43]
The current code suggests that something like 

    x | y > 5 in {1, 2, 3 && z in 4, 5, 6}

which should be forbidden according to the specs.

**Comment by eddiebergman** [comment]
I'd rather we freeze pcs support as is and just encourage json or yaml formats which do not require a custom string parser.

**Comment by eddiebergman** [comment]
Version 1.0.0 now suggests yaml/json output which is more structured and does not require a parser for an _unusual format_. If someone comes across this issue and requires this, please let us now and we can look into this!
