### ISSUE TITLE
KeyError for RandomConfigs

### ISSUE THREAD

**Issue by mlindauer** [automl/ConfigSpace#49]
Hi,
the ConfigSpace throws an unexpected error for random configurations. Here an example script (using the spear_qcp example in SMAC3:

```
import sys

from ConfigSpace.configuration_space import ConfigSpace
from ConfigSpace.io.pcs import read

# see SMAC3 spear_qcp example
with open("target_algorithm/spear-python/spear-params-mixed.pcs") as fp:
    pcs = fp.readlines()
    
cs = read(pcs_string=pcs)

for i in range(10000):
    config = cs.sample_configuration()
    
    #print(config)
    for p in config:
        try:
            print(config[p])
        except KeyError:
            print(p)
            print(config)
            sys.exit(1)
```

The output is:

```
KeyError
sp-clause-inversion
Configuration:
  sp-clause-activity-inc, Value: 0.5245793579385227
  sp-clause-decay, Value: 1.793762045021577
  sp-clause-del-heur, Value: '2'
  sp-first-restart, Value: 124
  sp-learned-clause-sort-heur, Value: '7'
  sp-learned-clauses-inc, Value: 1.172033997030427
  sp-learned-size-factor, Value: 0.7146238837315566
  sp-max-res-lit-inc, Value: 1.93385606282595
  sp-max-res-runs, Value: 25
  sp-orig-clause-sort-heur, Value: '15'
  sp-phase-dec-heur, Value: '5'
  sp-rand-phase-dec-freq, Value: '0.05'
  sp-rand-phase-scaling, Value: 0.6488652050952217
  sp-rand-var-dec-freq, Value: '0'
  sp-res-cutoff-cls, Value: 3
  sp-res-cutoff-lits, Value: 180
  sp-res-order-heur, Value: '8'
  sp-resolution, Value: '1'
  sp-restart-inc, Value: 1.3726376426746159
  sp-update-dec-queue, Value: '0'
  sp-use-pure-literal-rule, Value: '0'
  sp-var-activity-inc, Value: 0.512447739865641
  sp-var-dec-heur, Value: '16'
  sp-variable-decay, Value: 1.4303654243518888

Traceback (most recent call last):
  File "/home/lindauer/git/SMAC3/examples/spear_qcp/test_pcs.py", line 18, in <module>
    print(p, config[p])
  File "/home/lindauer/bin/anaconda3/lib/python3.5/site-packages/ConfigSpace-0.3.7-py3.5.egg/ConfigSpace/configuration_space.py", line 1053, in __getitem__
    raise KeyError()
KeyError
```

The weird think is that the error is not raised if I first print the configuration (see commented print within for-loop)

**Comment by mfeurer** [comment]
The `KeyError` is raised to make the `Configuration` behave more or less like a dictionary. An inactive hyperparameter is like something that's not in a dictionary and accessing it therefore raises a `KeyError`. Why calling `print(config)` circumvents this is a good question...

My proposal is that I check (might take me some time) why the call to `print` circumvents the error and fix that. What do you think?

**Comment by mlindauer** [comment]
I see your point.
But given your argument, I would expect either that
1. If I iterate over a configuration, I get all parameters and can access the values of all parameters (with None for inactive parameters) [that was implemented so far]
1. Or, I get only all active parameters and can also only access the values of such active parameters.

Right now, it seems to be mixed and inconsistent to me.

**Comment by mfeurer** [comment]
You're right, the current implementation is inconsistent in the way the iterator works. How about using `get()` instead of the indexing syntax as a workaround?

**Comment by mlindauer** [comment]
yes, this could be an interim solution. 
(however, I still wonder why it hits us only in some rare cases and why not the entire SMAC3 is broken)

**Comment by baothienpp** [comment]
Hi guys, i currently using ConfigSpace and having the exact same Error , the Error gone when i use print before accessing the parameters. Any fix so far ?
