### ISSUE TITLE
Broken pcs_new.write()

### ISSUE THREAD

**Issue by mlindauer** [automl/ConfigSpace#56]
Hi, unfortunately, the pcs_new.write() writes weird conditions, e.g.:

`(@1:counter-bump | @1:S:counterCond == 'yes' && @1:counter-bump | @1:0:restarts in {'F', 'D', 'L', 'x', '+'})`

pcs_new.read() also cannot read these conditions and complains.
I think correct would be:
`@1:counter-bump | @1:S:counterCond == 'yes' && @1:0:restarts in {'F', 'D', 'L', 'x', '+'}`

I hope it is easy to fix.

I attach both the original pcs file (clasp in the old pcs format) and the pcs file generated by pcs_new.write()

[pcs_old.txt](https://github.com/automl/ConfigSpace/files/1145039/pcs_old.txt)
[pcs_new.txt](https://github.com/automl/ConfigSpace/files/1145038/pcs_new.txt)

**Comment by KEggensperger** [comment]
By any chance: Is this valid SMAC2 Syntax?

**Comment by mlindauer** [comment]
'(@1:counter-bump | @1:S:counterCond == 'yes' && @1:counter-bump | @1:0:restarts in {'F', 'D', 'L', 'x', '+'})'

is not valid SMAC2 syntax. SMAC can't even read it.

**Comment by KEggensperger** [comment]
I pushed a quick fix. Please check out branch FIX#56 and try again.

**Comment by mlindauer** [comment]
Now, I get

`@1:S:Luby:aryrestarts | @1:0:restarts == L@1:counter-bump | @1:S:counterCond == yes && @1:0:restarts in {F, D, L, x, +}`

I think a line break is missing.
Except this, it looks fine.

**Comment by KEggensperger** [comment]
I expected something like this .. 
It should work now (at least your example does):

```
from ConfigSpace.io import pcs, pcs_new

with open("pcs_old.txt", "r") as fh:
    pcs_old = pcs.read(fh.readlines())

new_pcs = pcs_new.write(pcs_old)
pcs_new.read(new_pcs.split("\n"))
```

**Comment by mlindauer** [comment]
great. thanks. works well for me now.

**Comment by mfeurer** [comment]
I just merged the commit to master. I hope this helps.
