### ISSUE TITLE
Type contracts?

### ISSUE THREAD

**Issue by dvolgyes** [automl/ConfigSpace#61]
Hi,

I see that the code contains large amount of type hints.
This is useful for static analyzers, but as far as I know
python doesn't enforce anything runtime.

You might consider to use PyContracts.
https://pypi.python.org/pypi/PyContracts

In most simple cases, it can use the same type hints from,
and check them runtime.
On the other hand, pycontracts is quite powerful, 
and you can define more fine grained conditions, 
like a list must have at least 3 item long, or
a file path must exist, etc.

If it slows the code down, (it should not), 
then all the checks can be disabled with a single call.

**Comment by mfeurer** [comment]
Thank you for your suggestions. The package looks pretty cool. However, the code is already too slow and therefore compiled to Cython. In the current Cython release (not yet available via conda) there is an option to compile type hints to function argument declarations which we might do in the future, see this [changelog](https://github.com/cython/cython/blob/master/CHANGES.rst#features-added-2).

**Comment by dvolgyes** [comment]
I am happy that you find it interesting.
Actually, i found Pycontracts reasonably fast, and I would phrase it that
way:
as long as you decorate a python function, I did not find pycontracts as a
bottleneck.
When you need a lot of C-compiled function calls, then use Cython.
Pycontracts cannot decorate cython code, but there you have types.

In pure python mode, I found it fast enough (or can be turned off runtime,
e.g. you can test if it is running inside Travis, and enforce contracts for
the unit tests,
and if it is not Travis, then disable them.)

But implementing the contracts, even though they are simple, might not be
the best use of resources, and other cleanup efforts might have better
results.

Anyway, try it once for a pet project, and you will see if it is worth the
effort or not.

**Comment by mfeurer** [comment]
We are actually compiling the whole package by now and the type hints are therefore enforced in practice.
