### ISSUE TITLE
undefined symbol: __intel_sse2_strchr

### ISSUE THREAD

**Issue by mlindauer** [automl/ConfigSpace#64]
I have an issue with installing the new configspace version on Nemo (using anaconda).
Even using a complete newly installed anaconda, I get the following error.
Any ideas?

```
$ python 
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ConfigSpace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fr/fr_fr/fr_tl1023/anaconda3/lib/python3.6/site-packages/ConfigSpace/__init__.py", line 33, in <module>
    from ConfigSpace.configuration_space import Configuration, \
ImportError: /home/fr/fr_fr/fr_tl1023/anaconda3/lib/python3.6/site-packages/ConfigSpace/configuration_space.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strchr
```

**Comment by mfeurer** [comment]
Did you compile the ConfigSpace with GCC 7.2.0? This is most likely due to not using the same compiler as for the python interpreter.

**Comment by mlindauer** [comment]
I did the standard workflow to install SMAC.
I downloaded and installed Anaconda (the newest release),
I installed the gcc for anaconda: `conda install gxx_linux-64 gcc_linux-64 swig`
and I installed the smac requirements: `pip install -r requirements.txt`

I don't know how I can set the correct compiler for the Configspace since I'm running only  `pip install -r requirements.txt`

**Comment by mlindauer** [comment]
Ok, I was able to resolve this by uninstall Cython and ConfigSpace and reinstalling both. (Nevertheless, I don't understand why this happened)
