### ISSUE TITLE
Why does configspace.io does not work?

### ISSUE THREAD

**Issue by vchouksey** [automl/ConfigSpace#67]
guys,

Why does configspace.io does not work?

<img width="910" alt="screen shot 2018-01-11 at 19 30 14" src="https://user-images.githubusercontent.com/6507341/34840669-fcc5ff16-f705-11e7-9a05-5ce2bc2a3895.png">

**Comment by mfeurer** [comment]
Because you are trying to call a module which is not present in version 0.4.3 of ConfigSpace. Try using a version of 0.3.X.

**Comment by mfeurer** [comment]
Also, please paste the output instead of taking a screenshot in the future.

**Comment by vchouksey** [comment]
ok, I installed 0.3.9 configspace.io is still not present.
vishalnayanshi@ubuntu:~$ python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fanova
>>> import ConfigSpace
>>> from ConfigSpace.io.pcs_new import read
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ConfigSpace.io'
>>>

**Comment by vchouksey** [comment]
Done, I change in Anaconda3 site-packages and replace with ConfigSpace==0.3.9 folder 

>>> import fanova
>>> exit()
vishalnayanshi@ubuntu:~$ python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fanova
>>> import ConfigSpace
>>> from ConfigSpace.io.pcs_new import read
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ConfigSpace.io'
>>> exit()
vishalnayanshi@ubuntu:~$ python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fanova
>>> import pimp
>>> import ConfigSpace
>>> import ConfigSpace.io
>>> from ConfigSpace.io.pcs_new import read
>>> from ConfigSpace.io.pcs_new import write
>>>
