### ISSUE TITLE
documentation ?

### ISSUE THREAD

**Issue by willembressers** [automl/ConfigSpace#68]
This is not really an issue but rather an "_feature_" request..

Could you write any documentation about how we could use this module?

**My Goal:**
I hope i can use this module combined with auto-sklearn to export the (module + parameter)  configuration (preferably to an database). So i can load the configuration (from the Database) and train a model more dynamically.

**Comment by mfeurer** [comment]
I agree that documentation of this module would be great, but I don't think anyone on our side will have time in the near future to work on this. To do what you're interested, you're most likely interested in the functions `Configuration().to_dictionary()` and the constructor of the configuration object, which can be instantiated with a dictionary. Also, in case you look for general guidance on how to define a configuration space, please check [this tutorial](https://automl.github.io/SMAC3/stable/quickstart.html#using-smac-in-python-svm). If you have any specific questions, please do not hesitate to ask.

**Comment by amueller** [comment]
maybe add a link to that tutorial to the readme? not entirely on-topic but better than nothing?

**Comment by mfeurer** [comment]
Here's a first version of the documentation: https://automl.github.io/ConfigSpace/master/

Thanks to @PhMueller 

Please open (a) new issue(s) for improvement suggestions.
