### ISSUE TITLE
Save a hash of the configuration space as attribute

### ISSUE THREAD

**Issue by mfeurer** [automl/ConfigSpace#69]
whenever it is changed, so other applications can easily and cheaply keep track of the current state of the configuration space (calling `hash()` every time a configuration space comes by might be too expensive).

**Comment by eddiebergman** [comment]
Was there a concrete reason for this in mind? I do agree that if there is to be one, it should be pre-calculated on the use of `add`. Might break if someone doesn't modify it through the required interface, i.e. `space.value = modification`

**Comment by eddiebergman** [comment]
Closing this until there's a concrete example of needing it
