### ISSUE TITLE
Adding value to Categorical Parameter?

### ISSUE THREAD

**Issue by mlindauer** [automl/ConfigSpace#70]
Hi,

Is there a way to add a further value to an already existing parameter?
With some hacks, it was possible before 0.4.0; but after the introduction of Cython, I cannot access all attributes of a parameter anymore.

Best,
Marius

**Comment by mfeurer** [comment]
I don't think there's a way to add further values to an already existing parameter. What's the use case of this?

**Comment by mlindauer** [comment]
In my AutoFolio, a user can "configure" the configspace, i.e., a user can decide whether she/he wants to add a e.g., a classifier or not. Right now, I implemented this feature by adding step by step further values to a categorical value if the user wants to consider it in the configspace.

**Comment by mfeurer** [comment]
Hm, it was certainly not intended to be used like that, I'm usually building it the other way around: https://github.com/automl/auto-sklearn/blob/master/autosklearn/pipeline/components/classification/__init__.py#L108

Would there be a drawback in switching the creation order?
