### ISSUE TITLE
pip install fails if cython is not installed

### ISSUE THREAD

**Issue by sfalkner** [automl/ConfigSpace#74]
When installing the package without cython being installed this happens:

```
pip install ConfigSpace
Collecting ConfigSpace
  Downloading ConfigSpace-0.4.4.tar.gz (841kB)
    100% |████████████████████████████████| 849kB 316kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6w71v_pm/ConfigSpace/setup.py", line 4, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
```

Shouldn't there be a way to list cython as a dependency such that pip can install that first?

**Comment by mlindauer** [comment]
the same problem applies to numpy.

**Comment by bolau** [comment]
Yup, we ran into the numpy problem as well. It would be great if the setup.py could be free of such dependencies, otherwise you cannot install ConfigSpace into a fresh environment with one `pip install -r requirements.txt` call.

**Comment by bolau** [comment]
At least, others have the same problem: https://stackoverflow.com/questions/2379898/make-distutils-look-for-numpy-header-files-in-the-correct-place

**Comment by mfeurer** [comment]
I'd be happy about any pull request to solve this issue. One could for example start from the [auto-sklearn setup file](https://github.com/automl/auto-sklearn/blob/master/setup.py) where someone recently added this.

**Comment by bolau** [comment]
Cool, I'll take a look!

**Comment by mikeza** [comment]
Ran into this. See https://github.com/automl/auto-sklearn/issues/610

@bolau  are you working on this? I would consider doing it.

**Comment by mfeurer** [comment]
It looks like this isn't possible while we use `setup.py` (see [here](https://github.com/pypa/setuptools/issues/1317)) and we should actually use `pyproject.toml` (see [here](https://medium.com/@grassfedcode/pep-517-and-518-in-plain-english-47208ca8b7a6)).

Anyone still interested in picking this up?

**Comment by mfeurer** [comment]
Alright, I just added a `pyproject.toml` yesterday and created a new release (0.4.15). When using a recent version of `pip` it is now possible to install the ConfigSpace without having cython installed.
