### ISSUE TITLE
Removing inactive values from a configuration

### ISSUE THREAD

**Issue by shukon** [automl/ConfigSpace#76]
Hi,
I'm reading in configurations from a file. Those files contain values for inactive hyperparameters. I stumbled upon [this comment](https://github.com/automl/ConfigSpace/blob/3e826d6c8e648a0b7b3f0cd12ad47e7261b7e741/ConfigSpace/configuration_space.py#L949), which states that a method to remove inactive hyperparameters from a Configuration was, at some point, a ToDo.
I'd be glad to implement it, but I need a few pointers. To check if a parameter is active, I'd do the same as [checking the configuration](https://github.com/automl/ConfigSpace/blob/3e826d6c8e648a0b7b3f0cd12ad47e7261b7e741/ConfigSpace/configuration_space.py#L773-L789). Is that about right?
This would be extremely helpful for me and I'd be happy to try and add a method.

UPDATE: I found a [method to correct a sampled array](https://github.com/automl/ConfigSpace/blob/3e826d6c8e648a0b7b3f0cd12ad47e7261b7e741/ConfigSpace/c_util.pyx#L141). I think this is already doing what I intended.

**Comment by mfeurer** [comment]
There's also [this method](https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/util.py#L257) which is a wrapper around the method to correct a sampled array. Please close if this is what you're looking for.

**Comment by shukon** [comment]
Perfect, I didn't look in the right place. Thanks!
