### ISSUE TITLE
ValueError: Trying to set illegal value (whereas value seems legal)

### ISSUE THREAD

**Issue by janvanrijn** [automl/ConfigSpace#78]
Relevant stack trace (don't get more .. ):

```
ValueError: Trying to set illegal value '2077.1950945298586' forhyperparameter C, Type: UniformFloat, Range: [0.03125, 32768.0], Default: 1.0, on log-scale.
```

**Comment by janvanrijn** [comment]
I can't program anymore . 

(It was a string value)

**Comment by mfeurer** [comment]
Yeah, but the error message is not helpful, so I'll reopen it.

**Comment by shukon** [comment]
W.r.t. #100 I suggest the error message to be extended with types, because right now it just always looks as if we were setting a string.

**Comment by mfeurer** [comment]
Thanks a lot @shukon for fixing this in #101.
