### ISSUE TITLE
Conditional Parameters

### ISSUE THREAD

**Issue by janvanrijn** [automl/ConfigSpace#80]
One function that I commonly use within the OpenML spheres is 'filter setups according to config space'. For this I utilize the ConfigSpace library. I download a list of setups, give it a config space object and only keep the setups that are within this config space. I created a (non-perfect) version of it yesterday in the openml-python-contrib library:
https://github.com/openml/openml-python-contrib/blob/master/openmlcontrib/setups/functions.py

One thing that I couldn't figure out in the documentation of ConfigSpace: how to take into account hyperparameter conditionals. i.e., the libsvm_svc degree is only relevant when the poly kernel is selected. This knowledge is usually available in the Config Space, I just don't know how to extract it.

**Comment by janvanrijn** [comment]
Thanks for your quick reply. However, I don't think that this does what I am looking for. 

On OpenML, we store for all flows programmatically all values for all hyperparameters. This could for example be a legal flow:

```
{
'kernel': 'rbf',
'degree': 1,
'gamma': 0.125,
'C': 4
}
```

Although it is a RBF kernel, it would have gotten the degree value of 1 (I guess because this might be the default in sklearn).

In the ConfigSpace lib, I now use the `ConfigSpace.Configuration(config_space, name_values_dict)` function to check whether this is a legal configuration. Unfortunately, it does not recognize that the value of degree should not matter, so I want to remove this from the `name_values_dict`. The actual question is how to recognize hyperparameters whos values do not matter (here: degree), because they are actually dependend on a value that was not selected (here: kernel, because value != poly).

**Comment by janvanrijn** [comment]
I dived a little bit deeper into the code, and this part is what I need:

```
    def _check_configuration_rigorous(self, configuration: 'Configuration',
                                      allow_inactive_with_values: bool = False) -> None:
        vector = configuration.get_array()

        for hp_name, hyperparameter in self._hyperparameters.items():
            hp_value = vector[self._hyperparameter_idx[hp_name]]

            if not np.isnan(hp_value) and not hyperparameter.is_legal_vector(hp_value):
                raise ValueError("Hyperparameter instantiation '%s' "
                                 "(type: %s) is illegal for hyperparameter %s" %
                                 (hp_value, str(type(hp_value)),
                                  hyperparameter))

            conditions = self._parent_conditions_of[hyperparameter.name]

            active = True
            for condition in conditions:

                parent_vector_idx = condition.get_parents_vector()

                # if one of the parents is None, the hyperparameter cannot be
                # active! Else we have to check this
                # Note from trying to optimize this - this is faster than using
                # dedicated numpy functions and indexing
                if any([vector[i] != vector[i] for i in parent_vector_idx]):
                    active = False
                    break

                else:
                    if not condition.evaluate_vector(vector):
                        active = False
                        break
===== the code above is what I want to reuse, the code below makes assumptions that I can't work with ====
            if active and np.isnan(hp_value):
                raise ValueError("Active hyperparameter '%s' not specified!" %
                                 hyperparameter.name)

            if not allow_inactive_with_values and not active and \
                            not np.isnan(hp_value):
                raise ValueError("Inactive hyperparameter '%s' must not be "
                                 "specified, but has the vector value: '%s'." %
                                 (hp_name, hp_value))
        self._check_forbidden(vector)
```

At this point, the function knows which parameters are `active` and which not. If I were to create a PR that abstracts this functionality into a separate function, could that be acceptable?

**Comment by mfeurer** [comment]
Hm, what would the name of that function be and what would be its use case?

**Comment by janvanrijn** [comment]
The name would be `get_active_hyperparameters`. Use cases are plenty: 
* currently the configspace code that encapsulates this feature is in a rather long and hard-to-read function. It would make the code more modular, and easier to maintain/unit test
* other libraries can (regardless of their wild-card for inactive hyperparameters) check against this function which hyperparameters should be set to NaN in order to be able to re-instantiate a configuration. E.g., sklearn returns inactive hyperparameters currently as their default, which makes it hard to re-instantiate. 
* I assume this also makes the code-base of auto-sklearn easier :)

Let me know if I can create a PR and have a reasonable chance of acceptance

**Comment by mfeurer** [comment]
I agree that such a function should be public if someone wants to use it.

However, the function you are referring to is not actually used anywhere except in the unit tests where it tests other functions. Therefore, please create a new function with the desired behavior.

And yes, please go ahead and create a PR.
