### ISSUE TITLE
Boolean Constants

### ISSUE THREAD

**Issue by KEggensperger** [automl/ConfigSpace#86]
Constants cannot be defined as a Boolean, categoricals can:

```
from ConfigSpace.hyperparameters import CategoricalHyperparameter, Constant

# works
a = CategoricalHyperparameter("a", choices(True, False))

# does not work
b = Constant("b", value=True)
```

**Comment by eddiebergman** [comment]
Bumping this issue, it would allow for better Typing in `autosklearn` components that require boolean parameters.
```
class SomeComponent:
    def __init__(
       self, 
       somebool: str  
   ) -> None:
       self.somebool = True if somebool == "True" else False
``` 

From Python 3.8 onwards it could be made a little better with `somebool: Literal["True", "False"]` but it would be nice to have the Typing be `somebool: bool`
