### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by burkartM** [automl/ConfigSpace#87]
Using add_configuration_space with a configspace containing an AbstractConjunction results in a TypeError: 'module' object is not callable in:
https://github.com/automl/ConfigSpace/blob/58321ea76e3c34043a9250ba5ccda1f880447abc/ConfigSpace/conditions.pyx#L472-L473

copy is not callable and should be used similar to:
https://github.com/automl/ConfigSpace/blob/58321ea76e3c34043a9250ba5ccda1f880447abc/ConfigSpace/conditions.pyx#L197-L202

**Comment by mfeurer** [comment]
Thank you for reporting this issue. Would you like to create a pull request containing a fix for this issue?

**Comment by burkartM** [comment]
After fixing the error I encountered a new problem:
In add_configspace add_conditions is called which does apparently not work with Conjunctions, you will lose all conditions but one.

I created a PR #88 that should fix both issues.
