### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mfeurer** [automl/ConfigSpace#93]
Overview of missing parts of the documentation:

- [ ] Add docstrings to all modules
- [ ] Document the utils module
- [ ] Add an illustration of forbidden hyperparameters

**Comment by AlexisMignon** [comment]
Any plan to improve this ?

**Comment by mfeurer** [comment]
There's a PR in #91 which we can hopefully merge soon.

**Comment by mfeurer** [comment]
This was actually finished up in #116
