### ISSUE TITLE
Reset default values of ConfigSpace

### ISSUE THREAD

**Issue by thundercat95** [automl/ConfigSpace#94]
Hi,
Is it possible to reset the default values of a ConfigSpace?

**Comment by mfeurer** [comment]
Sorry, I must have missed this issue. What do you mean by 'reset'?

**Comment by PatriciaXiao** [comment]
Sometimes it shows "ValueError: Hyperparameter 'lr' is already in the configuration space." upon changing a value. Personally I don't know why but I'm also looking for a way to "reset" it.

**Comment by mfeurer** [comment]
Do you mean changing the default value of a hyperparameter which is already part of the configuration space?

**Comment by PatriciaXiao** [comment]
Oh thank you for replying, Matthias, I managed to get over this by using different names for different hyper-parameters. Yes you understand it correctly, half-a-month ago I wanted to update the value of existing hyper-parameters, but didn't find a proper way to do so. Now that I sidestep the issue so everything works out well.

**Comment by mfeurer** [comment]
Great that you found a solution. In general, there is no mechanism to update something that has been added to a configuration space. One can do it by changing that object, but there is no mechanism in place to ensure that the configuration space is still consistent afterwards.
