### ISSUE TITLE
ValueError for default value

### ISSUE THREAD

**Issue by firoz-aziz-ansari** [automl/ConfigSpace#97]
Whenever i set the default value lesser than 1e-10 for UniformFloatHyperparameter it raises ValueError

`ValueError                                Traceback (most recent call last)
<ipython-input-13-be455f804c45> in <module>()
     25 # For example, gamma can be either "auto" or a fixed float
     26 gamma = CategoricalHyperparameter("gamma", ["auto", "value"], default_value="auto")  # only rbf, poly, sigmoid
---> 27 gamma_value = UniformFloatHyperparameter("gamma_value", 1e-15, 8, default_value=1e-11)
     28 cs.add_hyperparameters([gamma, gamma_value])
     29 

ConfigSpace/hyperparameters.pyx in ConfigSpace.hyperparameters.UniformFloatHyperparameter.__init__()

ConfigSpace/hyperparameters.pyx in ConfigSpace.hyperparameters.UniformFloatHyperparameter.check_default()

ValueError: Illegal default value 0.0`

Not sure if i am doing something wrong

**Comment by mfeurer** [comment]
It appears that this [round](https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/hyperparameters.pyx#L404) is the issue.

**Comment by christophe-rannou** [comment]
Maybe it moved, the actual rounding error seems to come from [here](https://github.com/automl/ConfigSpace/blob/master/ConfigSpace/hyperparameters.pyx#L469)

**Comment by mfeurer** [comment]
I can't remember any more. Would anyone like to create a PR alleviating this issue?
